#! /bin/sh
PRIMARY=$(xrandr --query | grep " primary" | cut -d " " -f1)
OUTPUTS=$(xrandr --query | grep " connected" | grep -v " primary" | cut -d " " -f1)

bspc monitor %$PRIMARY -d cli web comm media

WKSP=4
for OUT in $OUTPUTS; do
  bspc monitor %$OUT -d $((WKSP=WKSP+1)) $((WKSP=WKSP+1))
done

$HOME/.config/polybar/launch

feh --bg-fill --randomize ~/Wallpapers/* &

bspc config single_monocle           true
bspc config pointer_follows_monitor  true
bspc config border_width             0
bspc config window_gap               5

bspc config split_ratio              0.56
bspc config borderless_monocle       true
bspc config gapless_monocle          true

bspc rule -a imv state=floating
bspc rule -a feh state=floating
bspc rule -a realvnc-vncviewer state=floating
bspc rule -a Ulauncher Preferences state=floating
bspc rule -a XEyes state=floating follow=on sticky=on

pgrep -x xeyes > /dev/null || xeyes -fg black &
